mysite/grama/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from django.views.generic import TemplateView
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)
from django.conf import settings
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^tender/$', views.post_list, name='post_list'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^pinbox/$', views.pinbox, name='pinbox'),
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^index/$', views.index, name='index'),
    url(r'^download/$', views.download, name='download'),
    url(r'^gindex/$', views.gindex, name='index'),
    url(r'^error/$', views.error, name='error'),
    url(r'^details/$', views.details, name='details'),
    url(r'^mdetails/$', views.mdetails, name='mdetails'),
    # url(r'^forms/$', views.post_forms, name='post_form'),
    url(r'^forms/$', views.post_tender, name='post_tender'),
    url(r'^bforms/$', views.birth, name='birth'),
    url(r'^dforms/$', views.death, name='death'),
    # for to send feedback
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^gmaps/$', views.gmaps, name='gmaps'),
    url(r'^login/$',login,{'template_name':'grama/login.html'}),
    url(r'^logout/$', logout, {'template_name': 'grama/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^service/$', views.service, name='service'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

]

#
# url(r'^reset-password/$', password_reset,name  ='reset_password'),
# url(r'^reset-password/done$', password_reset_done,name='password_reset_done'),
# # url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,name='password_reset_confirm '),
# url(r'^reset/password/confirm(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name='password_reset_confirm'),
# url(r'^reset-password/complete/$', password_reset_complete,name='password_reset_complete'),

mysite/mysite/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView




urlpatterns = [
    # url('^test/', include('django.contrib.auth.urls')),
    url(r'^',include('grama.urls')),
    url(r'^login/$', views.login_redirect, name='login_redirect'),
    url(r'admin/', admin.site.urls),
    url(r'^admin/login/$', views.login_redirect,name='login_redirect'),
    url(r'^grama/', include('grama.urls')),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^grama/',include('django.contrib.auth.urls')),

]
admin.site.site_header = _("Grama Panchayath")
admin.site.site_title = _("Grama Panchayath")

mysite/grama/models.py
from django.db import models
from django.contrib.auth.models import User ,AbstractUser
from django.db.models.signals import post_save
from django.core.validators import RegexValidator
from django.utils import timezone
from django.dispatch import receiver
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    place=models.CharField(max_length=200,default='NULL')
    text = models.TextField(null=True, default='NULL')
    Due_date = models.DateTimeField(default=timezone.now)
    EMD =models.IntegerField(default=0,)
    DOC_Fee =models.IntegerField(default=0)
    Notice_Type=models.CharField(max_length=100,default='NULL')
    Authority_Type=models.CharField(max_length=100,default='NULL')
    Product_Services=models.CharField(max_length=100,default='NULL')
    Doc_Sale_Starts= models.DateTimeField(default=timezone.now)
    Doc_Sale_Ends= models.DateTimeField(default=timezone.now)
    Doc_Submit_Before=models.DateTimeField(default=timezone.now)
    def publish(self):
        self.Due_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    email = models.EmailField(max_length=70,blank=True)
    image = models.ImageField(upload_to='profile_image', blank=True)
    role = models.CharField(max_length=25, default='NULL')



    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)



# tender Model
class Tender(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=255, blank=False)
    submitted_at = models.DateTimeField(default=timezone.now)
    posted_on = models.DateTimeField(default=timezone.now)
    Due_date = models.DateTimeField(default=timezone.now)
    EMD =models.IntegerField(default=0,)
    DOC_Fee =models.IntegerField(default=0)
    Notice_Type=models.CharField(max_length=100,default='NULL')
    Authority_Type=models.CharField(max_length=100,default='NULL')
    Product_Services=models.CharField(max_length=100,default='NULL')
    Doc_Sale_Starts= models.DateTimeField(default=timezone.now)
    Doc_Sale_Ends= models.DateTimeField(default=timezone.now)
    Doc_Submit_Before=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title
#
# def create_tender(sender, **kwargs):
#     if kwargs['created']:
#         user_profile = Tender.objects.create(user=kwargs['instance'])
#
# post_save.connect(create_profile, sender=User)
class Comment(models.Model):
    post = models.ForeignKey('grama.Post', related_name='comments')
    username = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text


# Details of the village Model
class Details(models.Model):
    village=models.CharField(max_length=100,default='')
    total_men =models.IntegerField()
    total_ladies =models.IntegerField()
    total_sc =models.IntegerField()
    total_st =models.IntegerField()
    total_Physical_Disabled =models.IntegerField()


    def __str__(self):
        return self.village
    class Meta:
        verbose_name_plural = "Details"

 # Details of the village Model
class VDetails(models.Model):
    village=models.CharField(max_length=100,default='')
    total_men =models.IntegerField()
    total_ladies =models.IntegerField()
    total_sc =models.IntegerField()
    total_st =models.IntegerField()
    total_Physical_Disabled =models.IntegerField()


    def __str__(self):
        return self.village
    class Meta:
        verbose_name_plural = "VDetails"

# Birth Certicate

class BirthCertificate(models.Model):
    issue_Date = models.DateField(default=timezone.now)
    id_Card_No=models.IntegerField(default=0)
    title = models.CharField(choices=((1,("Mr")),
                                            (2,("Mrs")),
                                            ),max_length=100)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    address = models.TextField(max_length=255, blank=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    email = models.EmailField(max_length=70,blank=True)
    childName =models.CharField(max_length=100)
    Place_Of_Birth=models.CharField(max_length=100)
    Date_Of_Birth= models.DateField(default=timezone.now)
    fatherName =models.CharField(max_length=100)
    motherName =models.CharField(max_length=100)
    ID_card_no_child= models.CharField(max_length=100)
    def __str__(self):
        return self.title


# Death Certicate

class DeathCertificate(models.Model):

    issue_Date = models.DateField(default=timezone.now)
    Sex = models.CharField(choices=((1,("Male")),
                                            (2,("Female")),
                                            ),max_length=100)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    address = models.TextField(max_length=255, blank=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    Date_of_Death=models.DateField(default=timezone.now)
    Place_of_Death =models.CharField(max_length=100)
    Place_Of_Birth=models.CharField(max_length=100)
    Date_Of_Birth= models.DateField(default=timezone.now)
    fatherName =models.CharField(max_length=100)
    motherName =models.CharField(max_length=100)
    adharcard_no= models.CharField(max_length=100)
    def __str__(self):
        return self.title



class Feedback(models.Model):
    name= models.CharField(max_length=100,default='')
    subject  = models.CharField(max_length=100)
    text = models.TextField(max_length=255, blank=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    email = models.EmailField(max_length=70,blank=True)
    issue_Date = models.DateField(default=timezone.now)
    def __str__(self):
        return self.name

mysite/grama/templates/citizen/bforms.html
{% extends 'base2.html'%}
{% load staticfiles %}
{% load static %}
{% block head %}<title>birth</title>
<style type="text/css">
#id_address{
  display: block;
}
 #reg{
   display: flex;
   justify-content: center;
   align-items: center;

 }
 body{
 background: rgba(192, 227, 187,0.9)!important;
 }

 form{
   padding: 30px;
   color:#000;
   background:#fff;
   width:430px;
   height: auto;
 }
 label{
   width:120px;
   font-size:15px;
   font-weight: normal;
 }
 input{
   padding:60 0px ;
   display:block;
  width:100%;
  border-radius: 3px;
  font: 400 13.3333px Arial;
  padding:1rem;
 }
 input:focus{
   border:1px solid #007bff;
 }

 span{
   font-size: 20px;
 }
button{
  padding:1rem;
}
.errorlist{
  color:red;
  list-style: none;
  position: relative;

}
#id_description{
  display: block;
}
.errorlist  li {
  font-size:12px;
  float: right;
  position:absolute;
  top: 70px;
  right: 0;
}
@media only screen and (max-width:620px){
  .helptext{
    display:none;
  }
  form{
    padding: 30px;
    color:#000;
    background-color:rgba(255,255,255,0.9);
    width:100%;
    width:100%;
    display:grid;
    grid-template-columns: 100%;

  }
  button{
    /* margin-left:20%;
    display:block;
    text-align:center;
    padding:20 30px;
    width:60%;

    font-size:20px;
    font-weight:400; */
  }
}


</style>

{% endblock %}
{% block body %}



    <!--==========================
    Header
  ============================-->

  <!--==========================-->



  <header id="header">
    <div class="container-fluid">

      <div id="logo" class="pull-left">
        <h1><a href="/" class="scrollto"><img width="40px" height="40px"src="{% static 'gramaimg/logo.png' %}" alt=""></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="#intro"><img src="img/logo.png" alt="" title="" /></a>-->
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li ><a href="/grama/profile">Home</a></li>
          <li class="menu-active" ><a href="/bforms/">BirthCertificate</a></li>

        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->


<div class="container " style="margin-top:130px;">

    <!-- <h1 style="margin-top:20px; font-size:30px;color:#fff;padding: 30px;font-weight:bold;text-align:center; background-color:#417690;">Sign in ,Here</h1> -->
    <!-- <form role="form" class="form-horizontal" method="post">
      <input type='hidden' name='csrfmiddlewaretoken' value='89GTVQ8VJHgYDYXugs51zwtm0iHJ4Vt7' />
        <div class="form-group">


              <div class="input-group">
                <span class="input-group-addon" style="background-color:#b77b48; color:white"><span class="glyphicon glyphicon-user"></span></span>
                <input class="form-control" id="id_username" maxlength="10" name="username" value="None" type="text" />

              </div>


              <div class="input-group">
                <span class="input-group-addon" style="background-color:#b77b48; color:white"><span class="glyphicon glyphicon-user"></span></span>
                <input class="form-control" id="id_password" maxlength="10" name="password" value="None" type="text" />

              </div>

        </div>
     <p><label for="id_username">Username:</label> <input id="id_username" maxlength="254" name="username" type="text" /></p>
<p><label for="id_password">Password:</label> <input id="id_password" name="password" type="password" /></p>

    </form> -->
    <div id="reg">

      <!-- <form class="form-horizontal m-t-20" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group text-center row m-t-20">
            <div class="col-12">
                <button class="btn btn-info btn-block waves-effect waves-light" type="submit">Log In</button>
            </div>
        </div>
             <button type="submit" class="btn btn-primary btn-lg" style="font-size:20px;width:60%;margin-left:20%;display:block;text-align:center;padding:20 30px;">Log in</button> -->
      <!-- </form>  -->
      <form class="form-horizontal m-t-20" method="post">


        <a href="/" class="scrollto" style="display:block;text-align:center;padding-bottom:3rem;"><img width="30px" height="30px"src="/static/gramaimg/logo.png" alt=""></a>
        <h4 style="display:block;text-align:center;font-weight:bold;font-size:2rem;">Birth Certificate</h4>
        {% csrf_token %}
          {{ form.as_p }}
          <div class="form-group row">
            <div class="col-12">
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                  <label style="width:100%;display:block;" class="custom-control-label font-weight-normal" for="customCheck1">I accept <a href="#" class="text-muted">Terms and Conditions</a></label>
              </div>
            </div>
          </div>
          <div class="form-group text-center row m-t-20">
              <div class="col-12">
                  <button class="btn btn-info btn-block waves-effect waves-light" style="font-size:1.4rem;padding:0.7rem;"type="submit">submit</button>
              </div>
          </div>


      </form>

    </div>
      <!-- <h2 style="font-weight:500;font-size:16px;display:block;text-align:center;padding-top:10px;"><a style="color:red;" target="_blank" href="/password_reset/">Forgot Password ?</a></h2> -->







</div>
<div style="min-height:100px;"></div>
<!-- Footer -->
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">

        <div class="col-lg-4 col-md-6 footer-info">
          <h3>Grama Panchayath</h3>
          <p>  </div>

        <div class="col-lg-4 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="ion-ios-arrow-right"></i> <a href="/">Home</a></li>
            <li><i class="ion-ios-arrow-right"></i> <a href="/">About us</a></li>
            <li><i class="ion-ios-arrow-right"></i> <a href="/grama/service">Services</a></li>


          </ul>
        </div>

        <div class="col-lg-4 col-md-6 footer-contact">
          <h4>Contact Us</h4>
          <p>
            Gram panchayth <br>
            Innoli,574531<br>
            Mangalore<br>
            <strong>Phone:</strong> +1 9108776988<br>
            <strong>Email:</strong> grama@example.com<br>
          </p>

          <div class="social-links">
            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
            <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
            <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
            <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
          </div>

        </div>


      </div>
    </div>
  </div>
  <div class="container">
    <div class="copyright">
      &copy; Copyright <strong>Government</strong>. All Rights Reserved
    </div>

  </div>
</footer><!-- #footer -->
<script type="text/javascript">
document.getElementById("id_username").setAttribute("placeholder", "Username");
document.getElementById("id_first_name").setAttribute("placeholder", "FirstName");
document.getElementById("id_last_name").setAttribute("placeholder", "LastName");
document.getElementById("id_email").setAttribute("placeholder", "Email");
document.getElementById("id_password1").setAttribute("placeholder", "Password");
document.getElementById("id_password2").setAttribute("placeholder", "Password");



</script>
{% endblock %}

mysite/grama/templates/citizen/complaint.html
{% extends 'base2.html'%}
{% load staticfiles %}
{% load static %}
{% block head %}<title>feedback</title>
<style type="text/css">
#id_address{
  display: block;
}
 #reg{
   display: flex;
   justify-content: center;
   align-items: center;

 }
 body{
 background: rgba(192, 227, 187,0.9)!important;
 }

 form{
   padding: 30px;
   color:#000;
   background:#fff;
   width:430px;
   height: auto;
 }
 label{
   width:120px;
   font-size:15px;
   font-weight: normal;
 }
 input{
   padding:60 0px ;
   display:block;
  width:100%;
  border-radius: 3px;
  font: 400 13.3333px Arial;
  padding:1rem;
 }
 input:focus{
   border:1px solid #007bff;
 }

 span{
   font-size: 20px;
 }
button{
  padding:1rem;
}
.errorlist{
  color:red;
  list-style: none;
  position: relative;

}
#id_description{
  display: block;
}
.errorlist  li {
  font-size:12px;
  float: right;
  position:absolute;
  top: 70px;
  right: 0;
}
@media only screen and (max-width:620px){
  .helptext{
    display:none;
  }
  form{
    padding: 30px;
    color:#000;
    background-color:rgba(255,255,255,0.9);
    width:100%;
    width:100%;
    display:grid;
    grid-template-columns: 100%;

  }
  button{
    /* margin-left:20%;
    display:block;
    text-align:center;
    padding:20 30px;
    width:60%;

    font-size:20px;
    font-weight:400; */
  }
}


</style>

{% endblock %}
{% block body %}



    <!--==========================
    Header
  ============================-->

  <!--==========================-->



  <header id="header">
    <div class="container-fluid">

      <div id="logo" class="pull-left">
        <h1><a href="/" class="scrollto"><img width="40px" height="40px"src="{% static 'gramaimg/logo.png' %}" alt=""></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="#intro"><img src="img/logo.png" alt="" title="" /></a>-->
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li ><a href="/grama/profile/">Home</a></li>
          <li class="menu-active" ><a href="/feedback/">Feedback</a></li>

        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->


<div class="container " style="margin-top:130px;">

    <!-- <h1 style="margin-top:20px; font-size:30px;color:#fff;padding: 30px;font-weight:bold;text-align:center; background-color:#417690;">Sign in ,Here</h1> -->
    <!-- <form role="form" class="form-horizontal" method="post">
      <input type='hidden' name='csrfmiddlewaretoken' value='89GTVQ8VJHgYDYXugs51zwtm0iHJ4Vt7' />
        <div class="form-group">


              <div class="input-group">
                <span class="input-group-addon" style="background-color:#b77b48; color:white"><span class="glyphicon glyphicon-user"></span></span>
                <input class="form-control" id="id_username" maxlength="10" name="username" value="None" type="text" />

              </div>


              <div class="input-group">
                <span class="input-group-addon" style="background-color:#b77b48; color:white"><span class="glyphicon glyphicon-user"></span></span>
                <input class="form-control" id="id_password" maxlength="10" name="password" value="None" type="text" />

              </div>

        </div>
     <p><label for="id_username">Username:</label> <input id="id_username" maxlength="254" name="username" type="text" /></p>
<p><label for="id_password">Password:</label> <input id="id_password" name="password" type="password" /></p>

    </form> -->
    <div id="reg">

      <!-- <form class="form-horizontal m-t-20" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group text-center row m-t-20">
            <div class="col-12">
                <button class="btn btn-info btn-block waves-effect waves-light" type="submit">Log In</button>
            </div>
        </div>
             <button type="submit" class="btn btn-primary btn-lg" style="font-size:20px;width:60%;margin-left:20%;display:block;text-align:center;padding:20 30px;">Log in</button> -->
      <!-- </form>  -->
      <form class="form-horizontal m-t-20" method="post">


        <a href="/" class="scrollto" style="display:block;text-align:center;padding-bottom:3rem;"><img width="30px" height="30px"src="/static/gramaimg/logo.png" alt=""></a>
        <h4 style="display:block;text-align:center;font-weight:bold;font-size:2rem;">Feedback</h4>
        {% csrf_token %}
          {{ form.as_p }}
          <div class="form-group row">
            <div class="col-12">
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                  <label style="width:100%;display:block;" class="custom-control-label font-weight-normal" for="customCheck1">I accept <a href="#" class="text-muted">Terms and Conditions</a></label>
              </div>
            </div>
          </div>
          <div class="form-group text-center row m-t-20">
              <div class="col-12">
                  <button class="btn btn-info btn-block waves-effect waves-light" style="font-size:1.4rem;padding:0.7rem;"type="submit">submit</button>
              </div>
          </div>


      </form>

    </div>
      <!-- <h2 style="font-weight:500;font-size:16px;display:block;text-align:center;padding-top:10px;"><a style="color:red;" target="_blank" href="/password_reset/">Forgot Password ?</a></h2> -->







</div>
<div style="min-height:100px;"></div>
<!-- Footer -->
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">

        <div class="col-lg-4 col-md-6 footer-info">
          <h3>Grama Panchayath</h3>
          <p>  </div>

        <div class="col-lg-4 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="ion-ios-arrow-right"></i> <a href="/">Home</a></li>
            <li><i class="ion-ios-arrow-right"></i> <a href="/">About us</a></li>
            <li><i class="ion-ios-arrow-right"></i> <a href="/grama/service">Services</a></li>


          </ul>
        </div>

        <div class="col-lg-4 col-md-6 footer-contact">
          <h4>Contact Us</h4>
          <p>
            Gram panchayth <br>
            Innoli,574531<br>
            Mangalore<br>
            <strong>Phone:</strong> +1 9108776988<br>
            <strong>Email:</strong> grama@example.com<br>
          </p>

          <div class="social-links">
            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
            <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
            <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
            <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
          </div>

        </div>


      </div>
    </div>
  </div>
  <div class="container">
    <div class="copyright">
      &copy; Copyright <strong>Government</strong>. All Rights Reserved
    </div>

  </div>
</footer><!-- #footer -->
<script type="text/javascript">


</script>
{% endblock %}

mysite/grama/templates/citizen/profile.html
{% extends 'base2.html'%}
{% load static %}

{% block head %}
<title>Profile</title>
<style media="screen">
  h1{
    font-size: 30px;
    font-weight: bolder;
    font-family: inherit;
    color: #444;
  }
  th,td{
    font-size: 20px;
    font-weight:400;
    font-family: inherit;
    color: #444;
  }
  /* Nav Menu Arrows */
.sf-arrows .sf-with-ul {
  padding-right: 30px;
}

.sf-arrows .sf-with-ul:after {
  content: "\f107";
  position: absolute;
  right: 15px;
  font-family: FontAwesome;
  font-style: normal;
  font-weight: normal;
}

.sf-arrows ul .sf-with-ul:after {
  content: "\f105";
}
</style>
{% endblock %}

{% block body %}
<header id="header">
  <div class="container-fluid">

    <div id="logo" class="pull-left">
      <h1><a href="/" class="scrollto"><img width="50px" height="50px"src="{% static 'gramaimg/logo.png' %}" alt=""></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="#intro"><img src="img/logo.png" alt="" title="" /></a>-->
    </div>

    <nav id="nav-menu-container">
      <ul class="nav-menu">
        <!-- <li class="menu-active"><a href="#intro">Home</a></li>
        <li><a href="#about">About Us</a></li>
        <li><a href="#services">Services</a></li>
        <li><a href="#portfolio">Portfolio</a></li> -->
        <!-- <li><a href="#team">Team</a></li> -->
        <li class="menu-has-children"><a href="#">welcome, {{user}}</a>
          <!-- <i class="fa fa-chevron-down"></i> -->
          <ul>
            <li><a href="/">viewSite</a></li>
            <li><a href="/grama/profile/edit">Edit Profile</a></li>
            <li><a href="/grama/logout">Log out</a></li>
            <!-- <li><a href="#">Drop Down 5</a></li> -->
          </ul>
        </li>
        <!-- <li><a href="#contact">Contact</a></li> -->
      </ul>
    </nav><!-- #nav-menu-container -->
  </div>
</header>
<div class="container">
    <!-- <h1>Profile</h1>
    <table class="table table-striped">
      <thead>
        <tr>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ user }}</td>
          <td>{{ user.first_name }}</td>
          <td>{{ user.last_name }}</td>
          <td>{{ user.email }}</td>
        </tr>
        <tr>
          <td colspan="2"> birth certifictae</td>
          <td colspan="2"><a class="btn btn-primary" target='_blank'href="http://dhss.delaware.gov/dph/ss/files/birth.pdf" download>date birth</a></td>

        </tr>
      </tbody>
    </table>



    {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">
    {% endif %} -->




</div>

</script>

{% endblock %}